[package]
name = "cypher-parser"
version = "0.1.0"
authors = ["leiysky <leiysky@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5"
unicode-xid = "0.0.4"